# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths U:/public/Lab5_Files_Ge/vga_display/axi_bram_8reg_1.0 [current_fileset]

read_ip u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/ip/color_map/color_map.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/ip/color_map/color_map.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir U:/public/Lab5_Files_Ge/vga_display/vga_display.data/wt [current_project]
set_property parent.project_dir U:/public/Lab5_Files_Ge/vga_display [current_project]
synth_design -top color_map -part xc7z020clg484-1 -mode out_of_context

rename_ref -prefix_all color_map
write_checkpoint -noxdef color_map.dcp
report_utilization -file color_map_utilization_synth.rpt -pb color_map_utilization_synth.pb
if { [catch {
  file copy -force U:/public/Lab5_Files_Ge/vga_display/vga_display.runs/color_map_synth_1/color_map.dcp u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/ip/color_map/color_map.dcp
  write_verilog -force -mode synth_stub u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/ip/color_map/color_map_stub.v
  write_verilog -force -mode funcsim u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/ip/color_map/color_map_funcsim.v
  write_vhdl -force -mode funcsim u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/ip/color_map/color_map_funcsim.vhdl
} _RESULT ] } { 
  puts "Critical Warning: Unable to successfully create or copy supporting IP files."
}
