# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/ip/color_map/color_map.xci
# IP: The module: 'color_map' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/ip/color_map/color_map_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'color_map'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/ip/color_map/color_map.xci
# IP: The module: 'color_map' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/ip/color_map/color_map_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'color_map'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
