# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths {
  U:/public/VGA_PS/myip_1.0
  U:/public/VGA_PS/TestIP_1.0
} [current_fileset]
read_verilog {
  U:/public/VGA_PS/myip_1.0/hdl/myip_v1_0_S00_AXI.v
  U:/public/VGA_PS/myip_1.0/hdl/myip_v1_0.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir U:/public/VGA_PS/edit_myip_v1_0.data/wt [current_project]
set_property parent.project_dir U:/public/VGA_PS [current_project]
synth_design -top myip_v1_0 -part xc7z020clg484-1
write_checkpoint myip_v1_0.dcp
report_utilization -file myip_v1_0_utilization_synth.rpt -pb myip_v1_0_utilization_synth.pb
