# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==CHAR_LIB_COMP_N || ORIG_REF_NAME==CHAR_LIB_COMP_N}]]
