# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/drop_box/constraints.xdc

# IP: ip/CHAR_LIB_COMP_N/CHAR_LIB_COMP_N.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_LIB_COMP_N || ORIG_REF_NAME==CHAR_LIB_COMP_N}]
