# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog {
  H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1/elec444_lab1.srcs/sources_1/new/slowclock.v
  H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1/elec444_lab1.srcs/sources_1/new/sevenSegCtrl.v
  H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1/elec444_lab1.srcs/sources_1/new/guessCounter.v
  H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1/elec444_lab1.srcs/sources_1/new/bouncer.v
  H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1/elec444_lab1.srcs/sources_1/new/bin2bcd.v
  H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1/elec444_lab1.srcs/sources_1/imports/elec444lab1fsm.v
  H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1/elec444_lab1.srcs/sources_1/imports/ELEC240Lab3/SevenSegmentDecoder.v
  H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1/elec444_lab1.srcs/sources_1/new/lab1NumberGuess.v
}
read_xdc H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1/elec444_lab1.srcs/constrs_1/new/numberGuess.xdc
set_property used_in_implementation false [get_files H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1/elec444_lab1.srcs/constrs_1/new/numberGuess.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1/elec444_lab1.data/wt [current_project]
set_property parent.project_dir H:/Users/ygg001.BUCKNELL/Desktop/elec444_lab1 [current_project]
synth_design -top lab1NumberGuess -part xc7z020clg484-1
write_checkpoint lab1NumberGuess.dcp
report_utilization -file lab1NumberGuess_utilization_synth.rpt -pb lab1NumberGuess_utilization_synth.pb
