# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths U:/public/Lab5_Files_Ge/vga_display/axi_bram_8reg_1.0 [current_fileset]
add_files U:/public/Lab5_Files_Ge/vga_display/vga_display.runs/color_map_synth_1/color_map.dcp
set_property used_in_implementation false [get_files U:/public/Lab5_Files_Ge/vga_display/vga_display.runs/color_map_synth_1/color_map.dcp]
set_property use_blackbox_stub false [get_files U:/public/Lab5_Files_Ge/vga_display/vga_display.runs/color_map_synth_1/color_map.dcp]

add_files U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/bd/system/system_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/bd/system/system.bd]

read_verilog {
  U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/imports/VGA_HDMI_Starter/i2c_sender.v
  U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/imports/VGA_HDMI_Starter/vga_generator.v
  U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/imports/VGA_HDMI_Starter/hdmi_ddr_output.v
  U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/imports/VGA_HDMI_Starter/convert_444_422.v
  U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/imports/VGA_HDMI_Starter/colour_space_conversion.v
  U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/imports/new/vga_bram.v
  U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/imports/VGA_HDMI_Starter/vga_hdmi.v
  U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/imports/hdl/system_wrapper.v
  U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/imports/new/system_top.v
  u:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/sources_1/ip/color_map/color_map_stub.v
}
read_xdc U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/constrs_1/imports/VGA_HDMI_Starter/zedboard_hdmi.xdc
set_property used_in_implementation false [get_files U:/public/Lab5_Files_Ge/vga_display/vga_display.srcs/constrs_1/imports/VGA_HDMI_Starter/zedboard_hdmi.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir U:/public/Lab5_Files_Ge/vga_display/vga_display.data/wt [current_project]
set_property parent.project_dir U:/public/Lab5_Files_Ge/vga_display [current_project]
synth_design -top system_top -part xc7z020clg484-1
write_checkpoint system_top.dcp
report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb
