# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0

add_files U:/private/psTest/psTest.srcs/sources_1/bd/pstest/pstest.bd
set_property used_in_implementation false [get_files -all u:/private/psTest/psTest.srcs/sources_1/bd/pstest/ip/pstest_processing_system7_0_0/pstest_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all U:/private/psTest/psTest.srcs/sources_1/bd/pstest/pstest_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files U:/private/psTest/psTest.srcs/sources_1/bd/pstest/pstest.bd]

read_verilog U:/private/psTest/psTest.srcs/sources_1/bd/pstest/hdl/pstest_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir U:/private/psTest/psTest.data/wt [current_project]
set_property parent.project_dir U:/private/psTest [current_project]
synth_design -top pstest_wrapper -part xc7z020clg484-1
write_checkpoint pstest_wrapper.dcp
report_utilization -file pstest_wrapper_utilization_synth.rpt -pb pstest_wrapper_utilization_synth.pb
