# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/public/VGA_PS/VGA_PS.srcs/sources_1/ip/color_table/color_table.xci
# IP: The module: 'color_table' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/public/VGA_PS/VGA_PS.srcs/sources_1/ip/color_table/color_table_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'color_table'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: u:/public/VGA_PS/VGA_PS.srcs/sources_1/ip/color_table/color_table.xci
# IP: The module: 'color_table' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/public/VGA_PS/VGA_PS.srcs/sources_1/ip/color_table/color_table_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'color_table'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
